import { useEffect, useState } from "react";
import { useListTransactions } from "@workspace/api-client-react";
import { formatNGN, formatTxType, getRiskBg, getFraudLabelBg } from "@/lib/utils";
import { BROWSER_TRANSACTIONS_CHANGED, getBrowserTransactions, type BrowserTransaction } from "@/lib/browserTransactions";
import { BrainCircuit, ArrowUp, ArrowDown, Minus } from "lucide-react";

function SHAPBar({ feature, value, importance, direction, description }: {
  feature: string; value: number; importance: number; direction: string; description: string;
}) {
  const isIncreasing = direction === "increases_risk";
  const isDecreasing = direction === "decreases_risk";
  const barColor = isIncreasing ? "bg-red-500" : isDecreasing ? "bg-emerald-500" : "bg-slate-400";
  const textColor = isIncreasing ? "text-red-600" : isDecreasing ? "text-emerald-600" : "text-muted-foreground";
  const Icon = isIncreasing ? ArrowUp : isDecreasing ? ArrowDown : Minus;

  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-1.5">
          <Icon className={`h-3.5 w-3.5 ${textColor}`} />
          <span className="text-sm font-medium">{feature}</span>
        </div>
        <span className={`text-sm font-semibold ${textColor}`}>
          {isIncreasing ? "+" : isDecreasing ? "-" : ""}{Math.round(importance * 100)}%
        </span>
      </div>
      <div className="relative h-5 bg-muted rounded overflow-hidden">
        <div
          className={`absolute top-0 h-full rounded ${barColor} opacity-80`}
          style={{
            width: `${importance * 100}%`,
            left: isDecreasing ? "auto" : 0,
            right: isDecreasing ? 0 : "auto",
          }}
        />
        <div className="absolute inset-0 flex items-center px-2">
          <span className="text-xs text-foreground/70 truncate">{description}</span>
        </div>
      </div>
    </div>
  );
}

export default function Explainability() {
  const [browserTransactions, setBrowserTransactions] = useState<BrowserTransaction[]>(() => getBrowserTransactions());

  useEffect(() => {
    const refreshBrowserTransactions = () => setBrowserTransactions(getBrowserTransactions());

    window.addEventListener(BROWSER_TRANSACTIONS_CHANGED, refreshBrowserTransactions);
    window.addEventListener("storage", refreshBrowserTransactions);

    return () => {
      window.removeEventListener(BROWSER_TRANSACTIONS_CHANGED, refreshBrowserTransactions);
      window.removeEventListener("storage", refreshBrowserTransactions);
    };
  }, []);

  const { data, isLoading } = useListTransactions(
    { limit: 50, flaggedOnly: true },
    ({ query: { refetchInterval: 15000 } } as unknown) as any
  );

  const apiTransactions = data?.transactions ?? [];
  const apiIds = new Set(apiTransactions.map(tx => tx.id));
  const combinedTransactions = [
    ...apiTransactions,
    ...browserTransactions.filter(tx => !apiIds.has(tx.id)),
  ];
  const flaggedTxns = combinedTransactions
    .filter(tx => tx.fraudLabel !== "clean" && tx.fraudAnalysis)
    .sort((a, b) => b.riskScore - a.riskScore)
    .slice(0, 8);

  return (
    <div className="p-8 space-y-6 max-w-6xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Explainable AI Panel</h1>
        <p className="text-muted-foreground text-sm mt-1">
          SHAP-style feature attributions explaining why each flagged transaction was identified as suspicious or fraudulent
        </p>
      </div>

      {/* Methodology note */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-5">
        <h2 className="font-semibold text-sm text-blue-800 mb-2">Explainability Methodology</h2>
        <p className="text-sm text-blue-700">
          This panel presents Shapley Additive Explanations (SHAP)-inspired feature attributions for each flagged transaction.
          Each bar shows a feature's contribution to the final risk score — red bars increase fraud probability,
          green bars decrease it. The explanations are generated by the ensemble model combining rule-based,
          anomaly detection, and logistic regression components. In a production deployment, these explanations
          would be generated by the SHAP library against a trained gradient boosting model (XGBoost/LightGBM).
        </p>
      </div>

      {isLoading && browserTransactions.length === 0 ? (
        <div className="space-y-4">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="bg-card border border-card-border rounded-lg p-6 animate-pulse space-y-3">
              <div className="h-5 bg-muted rounded w-1/3" />
              <div className="h-4 bg-muted rounded w-2/3" />
              <div className="space-y-2">
                {[...Array(4)].map((_, j) => <div key={j} className="h-8 bg-muted rounded" />)}
              </div>
            </div>
          ))}
        </div>
      ) : flaggedTxns.length === 0 ? (
        <div className="bg-card border border-card-border rounded-lg flex flex-col items-center justify-center py-24 text-center">
          <BrainCircuit className="h-12 w-12 text-muted-foreground/40 mb-4" />
          <p className="font-medium text-muted-foreground">No flagged transactions to explain</p>
          <p className="text-sm text-muted-foreground/70 mt-1">Generate transactions with fraud rate above 0% using the Simulator</p>
        </div>
      ) : (
        <div className="space-y-5">
          {flaggedTxns.map(tx => {
            const analysis = tx.fraudAnalysis as any;
            if (!analysis) return null;

            return (
              <div key={tx.id} className="bg-card border border-card-border rounded-lg overflow-hidden">
                {/* Header */}
                <div className={`px-6 py-4 flex items-center justify-between ${tx.fraudLabel === "fraudulent" ? "bg-red-50 border-b border-red-200" : "bg-amber-50 border-b border-amber-200"}`}>
                  <div className="flex items-center gap-3">
                    <span className={`font-bold text-lg ${getRiskBg(tx.riskScore)} px-3 py-1 rounded-lg`}>
                      {tx.riskScore}
                    </span>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-sm font-semibold">{tx.id}</span>
                        <span className={`text-xs px-2.5 py-0.5 rounded-full font-semibold capitalize ${getFraudLabelBg(tx.fraudLabel)}`}>
                          {tx.fraudLabel}
                        </span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        {formatTxType(tx.type)} · {formatNGN(tx.amount)} · {tx.senderLocation} · {tx.senderPhone}
                      </p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-xs text-muted-foreground">Model</p>
                    <p className="text-xs font-medium">{analysis.modelUsed}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">Confidence: {Math.round((analysis.confidence ?? 0) * 100)}%</p>
                  </div>
                </div>

                <div className="p-6 space-y-5">
                  {/* AI Explanation */}
                  <div className="bg-muted/30 rounded-lg p-4">
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">Plain-English Explanation</p>
                    <p className="text-sm">{analysis.explanation}</p>
                  </div>

                  {/* SHAP Bars */}
                  {analysis.featureImportance?.length > 0 && (
                    <div className="space-y-3">
                      <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Feature Attributions</p>
                      {analysis.featureImportance.map((f: any) => (
                        <SHAPBar
                          key={f.feature}
                          feature={f.feature}
                          value={f.value}
                          importance={f.importance}
                          direction={f.direction}
                          description={f.description}
                        />
                      ))}
                    </div>
                  )}

                  {/* Triggered Rules */}
                  {analysis.triggeredRules?.length > 0 && (
                    <div>
                      <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">Triggered Detection Rules</p>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                        {analysis.triggeredRules.map((rule: string) => (
                          <div key={rule} className="flex items-center gap-2 bg-red-50 border border-red-100 text-red-700 text-xs px-3 py-2 rounded-lg">
                            <span className="h-1.5 w-1.5 rounded-full bg-red-500 shrink-0" />
                            {rule}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
